# Generated by Django 3.1.7 on 2021-03-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolconfiguration',
            name='projectName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
